version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
  test-db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
